language: cpp

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - zlib1g-dev
      - zlib1g-dev:i386

compiler:
  - gcc
  - clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew search zlib ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zlib; fi
  - sudo pip install pytest 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y zlib1g-dev     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y zlib1g-dev:i386; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y g++    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake  ; fi

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=1 ../
  - make 
  - cd ./bin/test_functional
  - py.test . -v --exec_dir=. --data_dir=./xlsx_files
