language: c++

compiler:
  - gcc

install:
  - sudo pip install pytest
  - sudo apt-get update
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y zlib1g-dev:i386
  - sudo apt-get install -y g++
  - sudo apt-get install -y cmake

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=1 ../
  - make 
  - py.test . -v --exec_dir=. --data_dir=./xlsx_files
