os:
  - Visual Studio 2015
  - Visual Studio 2017

init: []

install: 
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - appveyor DownloadFile "http://zlib.net/zlib128-dll.zip"
  - 7z x -ozlib zlib128-dll.zip
  - dir

build_script:
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Release -DZLIB_LIBRARY="..\zlib\lib\zdll.lib" -DZLIB_INCLUDE_DIR="..\zlib\include" ../ 
  - nmake 

test_script:
  - copy ..\zlib\zlib.dll .\bin\test_functional
  - cd .\bin\test_functional
  - py.test . -v --exec_dir=. --data_dir=./xlsx_files

