os:
  - Visual Studio 2015
  - Visual Studio 2017

init: []

install: 
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - git clone https://github.com/madler/zlib
  - cd zlib
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release .
  - nmake
  - cd ..

build_script:
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Release -DZLIB_LIBRARY="C:\projects\libxlsxwriter-cpp\zlib\lib\zlib.lib" -DZLIB_INCLUDE_DIR="C:\projects\libxlsxwriter-cpp\zlib\" ../ 
  - nmake 

test_script:
  - copy C:\projects\libxlsxwriter-cpp\zlib\bin\zlib.dll C:\projects\libxlsxwriter-cpp\bin\test_functional
  - cd .\bin\test_functional
  - py.test . -v --exec_dir=. --data_dir=./xlsx_files

