os:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python27.10"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"

install: 
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - git clone https://github.com/madler/zlib
  - cd zlib
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release .
  - nmake
  - cd ..
  - pip install pytest

build_script:
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Release -DZLIB_LIBRARY="C:\projects\libxlsxwriter-cpp\zlib\zlib.lib" -DZLIB_INCLUDE_DIR="C:\projects\libxlsxwriter-cpp\zlib" -DCMAKE_INSTALL_PREFIX="C:\projects\libxlsxwriter-cpp\build" ..
  - nmake 

test_script:
  - copy C:\projects\libxlsxwriter-cpp\zlib\zlib.dll C:\projects\libxlsxwriter-cpp\build\bin\test_functional
  - cd bin\test_functional
  - python -m py.test . -v --exec_dir=. --data_dir=./xlsx_files

